disabled_rules:
  - trailing_whitespace
excluded: # paths to ignore during linting.
  - Carthage
  - Pods
# parameterized rules can be customized from this configuration file
line_length: 200
trailing_whitespace: false