disabled_rules:
  - trailing_whitespace
excluded: # paths to ignore during linting.
  - Carthage
  - Pods
# parameterized rules can be customized from this configuration file
line_length: 200
file_length: 600
type_body_length: 350
function_parameter_count: 8
type_name:
    min_length: 3
    max_length:
        warning: 40
        error: 50
trailing_whitespace: false
