osx_image: xcode9.1
language: swift

before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod repo update
- pod install

xcode_sdk: iphonesimulator11.1

script:
- xcodebuild -workspace Matchmore.xcworkspace -scheme Matchmore -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=11.1' test
- pod lib lint --allow-warnings