osx_image: xcode9.1
language: swift

before_install:
- export IOS_SIMULATOR_UDID=`instruments -s devices | grep "iPhone 6 (9.3" | awk -F '[ ]' '{print $4}' | awk -F '[\[]' '{print $2}' | sed 's/.$//'`
- echo $IOS_SIMULATOR_UDID
- open -a "simulator" --args -CurrentDeviceUDID $IOS_SIMULATOR_UDID
- gem install cocoapods # Since Travis is not always on latest version
- pod repo update
- pod install

xcode_sdk: iphonesimulator11.1

script:
- xcodebuild -workspace AlpsSDK.xcworkspace -scheme AlpsSDK -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=11.1' test
- pod lib lint --allow-warnings