osx_image: xcode9.1
language: swift

before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod repo update
- pod install

xcode_sdk: iphonesimulator11.0

script:
- xcodebuild -workspace AlpsSDK.xcworkspace -scheme AlpsSDK -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=11.0' test
- pod lib lint --allow-warnings