osx_image: xcode9.1
language: swift

before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install

xcode_sdk: iphonesimulator11.0

script:
- xcodebuild clean build test -workspace AlpsSDK.xcworkspace -scheme AlpsSDKTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
- pod lib lint